# -*- coding: utf-8 -*-
"""cats vs dogs cnn model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sX3-HPba1DJFBu4Xef5F70-I6Up-7XRe
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import  ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPooling2D

!cp -r /content/drive/MyDrive/dataset /content/

#pre processing
data_gen=ImageDataGenerator(rescale=1./255.0)
train_data=data_gen.flow_from_directory(
"/content/drive/MyDrive/dataset/train",
target_size=(150,150),
class_mode='binary',
batch_size=128

)
val_data=data_gen.flow_from_directory(
"/content/drive/MyDrive/dataset/test",
target_size=(150,150),
class_mode='binary',
batch_size=128
)

print("Train samples:", train_data.samples)
print("Validation samples:", val_data.samples)

train_data.class_indices

#Build CNN model
model=Sequential()
model.add(Conv2D(32,(3,3),activation="relu",input_shape=(150,150,3)))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(3,3))
model.add(Conv2D(128,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

#compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

#training the model
model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

#test on a new image
from tensorflow.keras.preprocessing import image
import numpy as np
img_path="/content/closeup-shot-beautiful-ginger-domestic-kitten-sitting-white-surface.jpg"
img=image.load_img(
    img_path,
    target_size=(150,150)
)
img_array=image.img_to_array(img)
img_array=img_array/255.0
img_array=np.expand_dims(img_array,axis=0)
result=model.predict(img_array)
if result[0][0]>0.5:
  print("dog")
else:
  print("cat")

model.save("cat_dog_model.h5")
print("Model saved successfully!")

